/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FarmerRouteImport } from './routes/_farmer'
import { Route as OfficerRouteImport } from './routes/_officer'
import { Route as OpsRouteImport } from './routes/_ops'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authNoAccessRouteImport } from './routes/(auth)/no-access'
import { Route as authSelectRoleRouteImport } from './routes/(auth)/select-role'
import { Route as FarmerFarmRouteImport } from './routes/_farmer/farm'
import { Route as OfficerOfficerRouteImport } from './routes/_officer/officer'
import { Route as OpsOpsRouteImport } from './routes/_ops/ops'
import { Route as OpsOpsIndexRouteImport } from './routes/_ops/ops.index'
import { Route as OpsOpsTowerRouteImport } from './routes/_ops/ops.tower'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerRoute = FarmerRouteImport.update({
  id: '/_farmer',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerRoute = OfficerRouteImport.update({
  id: '/_officer',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/_ops',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authNoAccessRoute = authNoAccessRouteImport.update({
  id: '/(auth)/no-access',
  path: '/no-access',
  getParentRoute: () => rootRouteImport,
} as any)
const authSelectRoleRoute = authSelectRoleRouteImport.update({
  id: '/(auth)/select-role',
  path: '/select-role',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerFarmRoute = FarmerFarmRouteImport.update({
  id: '/farm',
  path: '/farm',
  getParentRoute: () => FarmerRoute,
} as any)
const OfficerOfficerRoute = OfficerOfficerRouteImport.update({
  id: '/officer',
  path: '/officer',
  getParentRoute: () => OfficerRoute,
} as any)
const OpsOpsRoute = OpsOpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => OpsRoute,
} as any)
const OpsOpsIndexRoute = OpsOpsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OpsOpsRoute,
} as any)
const OpsOpsTowerRoute = OpsOpsTowerRouteImport.update({
  id: '/tower',
  path: '/tower',
  getParentRoute: () => OpsOpsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/no-access': typeof authNoAccessRoute
  '/select-role': typeof authSelectRoleRoute
  '/farm': typeof FarmerFarmRoute
  '/officer': typeof OfficerOfficerRoute
  '/ops': typeof OpsOpsRouteWithChildren
  '/ops/tower': typeof OpsOpsTowerRoute
  '/ops/': typeof OpsOpsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/no-access': typeof authNoAccessRoute
  '/select-role': typeof authSelectRoleRoute
  '/farm': typeof FarmerFarmRoute
  '/officer': typeof OfficerOfficerRoute
  '/ops/tower': typeof OpsOpsTowerRoute
  '/ops': typeof OpsOpsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_farmer': typeof FarmerRouteWithChildren
  '/_officer': typeof OfficerRouteWithChildren
  '/_ops': typeof OpsRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/no-access': typeof authNoAccessRoute
  '/(auth)/select-role': typeof authSelectRoleRoute
  '/_farmer/farm': typeof FarmerFarmRoute
  '/_officer/officer': typeof OfficerOfficerRoute
  '/_ops/ops': typeof OpsOpsRouteWithChildren
  '/_ops/ops/tower': typeof OpsOpsTowerRoute
  '/_ops/ops/': typeof OpsOpsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/no-access'
    | '/select-role'
    | '/farm'
    | '/officer'
    | '/ops'
    | '/ops/tower'
    | '/ops/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/no-access'
    | '/select-role'
    | '/farm'
    | '/officer'
    | '/ops/tower'
    | '/ops'
  id:
    | '__root__'
    | '/'
    | '/_farmer'
    | '/_officer'
    | '/_ops'
    | '/(auth)/login'
    | '/(auth)/no-access'
    | '/(auth)/select-role'
    | '/_farmer/farm'
    | '/_officer/officer'
    | '/_ops/ops'
    | '/_ops/ops/tower'
    | '/_ops/ops/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FarmerRoute: typeof FarmerRouteWithChildren
  OfficerRoute: typeof OfficerRouteWithChildren
  OpsRoute: typeof OpsRouteWithChildren
  authLoginRoute: typeof authLoginRoute
  authNoAccessRoute: typeof authNoAccessRoute
  authSelectRoleRoute: typeof authSelectRoleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_farmer': {
      id: '/_farmer'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof FarmerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_officer': {
      id: '/_officer'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof OfficerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_ops': {
      id: '/_ops'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/no-access': {
      id: '/(auth)/no-access'
      path: '/no-access'
      fullPath: '/no-access'
      preLoaderRoute: typeof authNoAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/select-role': {
      id: '/(auth)/select-role'
      path: '/select-role'
      fullPath: '/select-role'
      preLoaderRoute: typeof authSelectRoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_farmer/farm': {
      id: '/_farmer/farm'
      path: '/farm'
      fullPath: '/farm'
      preLoaderRoute: typeof FarmerFarmRouteImport
      parentRoute: typeof FarmerRoute
    }
    '/_officer/officer': {
      id: '/_officer/officer'
      path: '/officer'
      fullPath: '/officer'
      preLoaderRoute: typeof OfficerOfficerRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/_ops/ops': {
      id: '/_ops/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsOpsRouteImport
      parentRoute: typeof OpsRoute
    }
    '/_ops/ops/': {
      id: '/_ops/ops/'
      path: '/'
      fullPath: '/ops/'
      preLoaderRoute: typeof OpsOpsIndexRouteImport
      parentRoute: typeof OpsOpsRoute
    }
    '/_ops/ops/tower': {
      id: '/_ops/ops/tower'
      path: '/tower'
      fullPath: '/ops/tower'
      preLoaderRoute: typeof OpsOpsTowerRouteImport
      parentRoute: typeof OpsOpsRoute
    }
  }
}

interface FarmerRouteChildren {
  FarmerFarmRoute: typeof FarmerFarmRoute
}

const FarmerRouteChildren: FarmerRouteChildren = {
  FarmerFarmRoute: FarmerFarmRoute,
}

const FarmerRouteWithChildren =
  FarmerRoute._addFileChildren(FarmerRouteChildren)

interface OfficerRouteChildren {
  OfficerOfficerRoute: typeof OfficerOfficerRoute
}

const OfficerRouteChildren: OfficerRouteChildren = {
  OfficerOfficerRoute: OfficerOfficerRoute,
}

const OfficerRouteWithChildren =
  OfficerRoute._addFileChildren(OfficerRouteChildren)

interface OpsOpsRouteChildren {
  OpsOpsTowerRoute: typeof OpsOpsTowerRoute
  OpsOpsIndexRoute: typeof OpsOpsIndexRoute
}

const OpsOpsRouteChildren: OpsOpsRouteChildren = {
  OpsOpsTowerRoute: OpsOpsTowerRoute,
  OpsOpsIndexRoute: OpsOpsIndexRoute,
}

const OpsOpsRouteWithChildren =
  OpsOpsRoute._addFileChildren(OpsOpsRouteChildren)

interface OpsRouteChildren {
  OpsOpsRoute: typeof OpsOpsRouteWithChildren
}

const OpsRouteChildren: OpsRouteChildren = {
  OpsOpsRoute: OpsOpsRouteWithChildren,
}

const OpsRouteWithChildren = OpsRoute._addFileChildren(OpsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FarmerRoute: FarmerRouteWithChildren,
  OfficerRoute: OfficerRouteWithChildren,
  OpsRoute: OpsRouteWithChildren,
  authLoginRoute: authLoginRoute,
  authNoAccessRoute: authNoAccessRoute,
  authSelectRoleRoute: authSelectRoleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
